language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"


  matrix:
  #- LINT_CHECK="1"
  - TRANSIFEX="1"


after_success:
  - travis_after_tests_success
